# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setObjectName("toolBox")
        self.pageEncode = QtWidgets.QWidget()
        self.pageEncode.setGeometry(QtCore.QRect(0, 0, 69, 560))
        self.pageEncode.setObjectName("pageEncode")
        self.toolBox.addItem(self.pageEncode, "")
        self.pageEncrypt = QtWidgets.QWidget()
        self.pageEncrypt.setGeometry(QtCore.QRect(0, 0, 69, 560))
        self.pageEncrypt.setObjectName("pageEncrypt")
        self.toolBox.addItem(self.pageEncrypt, "")
        self.pageHex = QtWidgets.QWidget()
        self.pageHex.setGeometry(QtCore.QRect(0, 0, 69, 560))
        self.pageHex.setObjectName("pageHex")
        self.toolBox.addItem(self.pageHex, "")
        self.pageHash = QtWidgets.QWidget()
        self.pageHash.setObjectName("pageHash")
        self.toolBox.addItem(self.pageHash, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_src = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_src.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_src.setObjectName("verticalLayout_src")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.srcLineEdit1 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcLineEdit1.sizePolicy().hasHeightForWidth())
        self.srcLineEdit1.setSizePolicy(sizePolicy)
        self.srcLineEdit1.setObjectName("srcLineEdit1")
        self.horizontalLayout_2.addWidget(self.srcLineEdit1)
        self.srcLineEdit2 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcLineEdit2.sizePolicy().hasHeightForWidth())
        self.srcLineEdit2.setSizePolicy(sizePolicy)
        self.srcLineEdit2.setObjectName("srcLineEdit2")
        self.horizontalLayout_2.addWidget(self.srcLineEdit2)
        self.srcReplaceButton = QtWidgets.QPushButton(self.layoutWidget)
        self.srcReplaceButton.setObjectName("srcReplaceButton")
        self.horizontalLayout_2.addWidget(self.srcReplaceButton)
        self.srcClearButton = QtWidgets.QPushButton(self.layoutWidget)
        self.srcClearButton.setObjectName("srcClearButton")
        self.horizontalLayout_2.addWidget(self.srcClearButton)
        self.srcCopyButton = QtWidgets.QPushButton(self.layoutWidget)
        self.srcCopyButton.setObjectName("srcCopyButton")
        self.horizontalLayout_2.addWidget(self.srcCopyButton)
        self.srcPasteButton = QtWidgets.QPushButton(self.layoutWidget)
        self.srcPasteButton.setObjectName("srcPasteButton")
        self.horizontalLayout_2.addWidget(self.srcPasteButton)
        self.srcOpenButton = QtWidgets.QPushButton(self.layoutWidget)
        self.srcOpenButton.setObjectName("srcOpenButton")
        self.horizontalLayout_2.addWidget(self.srcOpenButton)
        self.verticalLayout_src.addLayout(self.horizontalLayout_2)
        self.srcTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.srcTextEdit.setPlainText("")
        self.srcTextEdit.setObjectName("srcTextEdit")
        self.verticalLayout_src.addWidget(self.srcTextEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_dst = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_dst.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_dst.setObjectName("verticalLayout_dst")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dstLineEdit1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.dstLineEdit1.setObjectName("dstLineEdit1")
        self.horizontalLayout_3.addWidget(self.dstLineEdit1)
        self.dstLineEdit2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.dstLineEdit2.setObjectName("dstLineEdit2")
        self.horizontalLayout_3.addWidget(self.dstLineEdit2)
        self.swapButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.swapButton.setObjectName("swapButton")
        self.horizontalLayout_3.addWidget(self.swapButton)
        self.dstReplaceButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.dstReplaceButton.setObjectName("dstReplaceButton")
        self.horizontalLayout_3.addWidget(self.dstReplaceButton)
        self.dstClearButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.dstClearButton.setObjectName("dstClearButton")
        self.horizontalLayout_3.addWidget(self.dstClearButton)
        self.dstCopyButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.dstCopyButton.setObjectName("dstCopyButton")
        self.horizontalLayout_3.addWidget(self.dstCopyButton)
        self.dstPasteButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.dstPasteButton.setObjectName("dstPasteButton")
        self.horizontalLayout_3.addWidget(self.dstPasteButton)
        self.dstSaveButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.dstSaveButton.setObjectName("dstSaveButton")
        self.horizontalLayout_3.addWidget(self.dstSaveButton)
        self.verticalLayout_dst.addLayout(self.horizontalLayout_3)
        self.dstTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        self.dstTextEdit.setObjectName("dstTextEdit")
        self.verticalLayout_dst.addWidget(self.dstTextEdit)
        self.horizontalLayout.addWidget(self.splitter)
        self.toolBox_2 = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_2.sizePolicy().hasHeightForWidth())
        self.toolBox_2.setSizePolicy(sizePolicy)
        self.toolBox_2.setObjectName("toolBox_2")
        self.pageDecode = QtWidgets.QWidget()
        self.pageDecode.setGeometry(QtCore.QRect(0, 0, 69, 612))
        self.pageDecode.setObjectName("pageDecode")
        self.toolBox_2.addItem(self.pageDecode, "")
        self.pageDecrypt = QtWidgets.QWidget()
        self.pageDecrypt.setGeometry(QtCore.QRect(0, 0, 69, 612))
        self.pageDecrypt.setObjectName("pageDecrypt")
        self.toolBox_2.addItem(self.pageDecrypt, "")
        self.horizontalLayout.addWidget(self.toolBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 23))
        self.menubar.setObjectName("menubar")
        self.menuEncode = QtWidgets.QMenu(self.menubar)
        self.menuEncode.setObjectName("menuEncode")
        self.menuDecode = QtWidgets.QMenu(self.menubar)
        self.menuDecode.setObjectName("menuDecode")
        self.menuEncrypt = QtWidgets.QMenu(self.menubar)
        self.menuEncrypt.setObjectName("menuEncrypt")
        self.menuDecrypt = QtWidgets.QMenu(self.menubar)
        self.menuDecrypt.setObjectName("menuDecrypt")
        self.menuHex = QtWidgets.QMenu(self.menubar)
        self.menuHex.setObjectName("menuHex")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuEncode.menuAction())
        self.menubar.addAction(self.menuDecode.menuAction())
        self.menubar.addAction(self.menuEncrypt.menuAction())
        self.menubar.addAction(self.menuDecrypt.menuAction())
        self.menubar.addAction(self.menuHex.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(0)
        self.dstClearButton.clicked.connect(self.dstTextEdit.clear)
        self.srcClearButton.clicked.connect(self.srcTextEdit.clear)
        self.dstPasteButton.clicked.connect(self.dstTextEdit.paste)
        self.srcPasteButton.clicked.connect(self.srcTextEdit.paste)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CTFCodecTool"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageEncode), _translate("MainWindow", "编码"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageEncrypt), _translate("MainWindow", "古典加密"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageHex), _translate("MainWindow", "进制转换"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageHash), _translate("MainWindow", "Hash"))
        self.srcLineEdit1.setPlaceholderText(_translate("MainWindow", "参数1"))
        self.srcLineEdit2.setPlaceholderText(_translate("MainWindow", "参数2"))
        self.srcReplaceButton.setText(_translate("MainWindow", "替换"))
        self.srcClearButton.setText(_translate("MainWindow", "清空"))
        self.srcCopyButton.setText(_translate("MainWindow", "复制"))
        self.srcPasteButton.setText(_translate("MainWindow", "粘贴"))
        self.srcOpenButton.setText(_translate("MainWindow", "打开文件"))
        self.dstLineEdit1.setPlaceholderText(_translate("MainWindow", "参数3"))
        self.dstLineEdit2.setPlaceholderText(_translate("MainWindow", "参数4"))
        self.swapButton.setText(_translate("MainWindow", "上下交换"))
        self.dstReplaceButton.setText(_translate("MainWindow", "替换"))
        self.dstClearButton.setText(_translate("MainWindow", "清空"))
        self.dstCopyButton.setText(_translate("MainWindow", "复制"))
        self.dstPasteButton.setText(_translate("MainWindow", "粘贴"))
        self.dstSaveButton.setText(_translate("MainWindow", "保存文件"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.pageDecode), _translate("MainWindow", "解码"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.pageDecrypt), _translate("MainWindow", "古典解密"))
        self.menuEncode.setTitle(_translate("MainWindow", "编码"))
        self.menuDecode.setTitle(_translate("MainWindow", "解码"))
        self.menuEncrypt.setTitle(_translate("MainWindow", "加密"))
        self.menuDecrypt.setTitle(_translate("MainWindow", "解密"))
        self.menuHex.setTitle(_translate("MainWindow", "进制转换"))
